apiVersion: v2
name: ssoerator
description: A Helm chart for SSOerator
sources:
  - https://github.com/FINTLabs/ssoerator/tree/main/charts/ssoerator
type: application
version: 0.1.0
appVersion: "0.0.0"
