apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ssoerator.fullname" . }}
  labels:
    {{- include "ssoerator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "ssoerator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "ssoerator.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "ssoerator.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- with .Values.env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- if .Values.config.environment }}
            - name: fint.operator.environment
              value: {{ .Values.config.environment | quote }}
            {{- end }}
            {{- if ne (.Values.config.testEnvironment | toString) "" }}
            - name: flais.operators.ssoerator.test-environment
              value: {{ .Values.config.testEnvironment | quote }}
            {{- end }}
            {{- if .Values.config.middlewareImage }}
            - name: flais.operators.ssoerator.middleware-image
              value: {{ .Values.config.middlewareImage | quote }}
            {{- end }}
          envFrom:
            - secretRef:
                name: {{ include "ssoerator.secretName" . }}
            {{- with .Values.extraEnvFrom }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
