apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ name }}
  namespace: {{ namespace }}
data:
  spring.webflux.base-path: {{ basePath }}
  fint.sso.issuer-uri: {{ issuerUri}}
  logging.level.no.fintlabs: {{ loggingLevel }}
  fint.sso.claim-for-upn: {{ upnClaim }}