apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ name }}
  namespace: {{ namespace }}
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`{{ hostname }}`) && PathPrefix(`{{ basePath }}{{ oauthPath }}`)
      kind: Rule
      services:
        - name: {{ name }}
          port: 8080