apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ name }}
  namespace: {{ namespace }}
spec:
  forwardAuth:
    address: http://{{ name }}.{{ namespace }}:8080{{ basePath }}{{ oauthPath }}
    authResponseHeaders:
      - Authorization
    trustForwardHeader: true