apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - patch: |-
      - op: add
        path: "/spec/template/spec/containers/0/env/-"
        value:
          name: fint.operator.environment
          value: api
    target:
      kind: Deployment
      name: ssoerator
  - patch: |-
      - op: add
        path: "/spec/template/spec/containers/0/env/-"
        value:
          name: flais.operators.ssoerator.test-environment
          value: "false"
    target:
      kind: Deployment
      name: ssoerator
  - patch: |-
      - op: replace
        path: "/spec/itemPath"
        value: "vaults/aks-api-vault/items/ssoerator"
    target:
      kind: OnePasswordItem
      name: ssoerator