apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ssoerator
rules:
  - apiGroups:
      - ""
      - "apps"
    resources:
      - secrets
      - configmaps
      - deployments
      - services
    verbs: 
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - get
      - list
  - apiGroups:
      - fintlabs.no
      - traefik.containo.us
    resources:
      - "*"
#      - namoauthclientapplicationresources
#      - namoauthclientapplicationresources/finalizers
#      - namoauthclientapplicationresources/status
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - patch
      - update