kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ssoerator
subjects:
- kind: ServiceAccount
  name: ssoerator
  namespace: operators
roleRef:
  kind: ClusterRole
  name: ssoerator
  apiGroup: rbac.authorization.k8s.io